In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to print the NumPy version in your system.

print(np.__version__)

1.17.2


In [3]:
# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

lst = [12.23, 13.32, 100, 36.32]
print(np.array(lst))

[ 12.23  13.32 100.    36.32]


In [4]:
# 3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
# 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [6]:
# 5. Write a NumPy program to create an array with values ranging from 12 to 38.

x = np.arange(12,39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [7]:
# 6. Write a NumPy program to reverse an array (first element becomes last).

x = np.array([1,2,0,9,6,4])
print(x)
print(x[::-1])

[1 2 0 9 6 4]
[4 6 9 0 2 1]


In [8]:
# 7. Write a NumPy program to convert an array to a float type.

x = np.array([18,25,10,19,61,14])
print(x)
print(x.astype('float32'))

[18 25 10 19 61 14]
[18. 25. 10. 19. 61. 14.]


In [9]:
# 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

x = np.ones(16).reshape(4,4)
print(x)
y = np.zeros(4).reshape(2,2)
print(y)
x[1:3,1:3] = y
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [10]:
# 9. Write a NumPy program to add a border (filled with 0's) around an existing array. 

x = np.ones(16).reshape(4,4)
print(x)
x = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. 

x = np.zeros(64).reshape(8,8)
#print(x)
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [12]:
# 11. Write a NumPy program to convert a list and tuple into arrays.

lst = [1,2,7,0,4,8]
print(np.array(lst))
#print(np.asarray(lst)) 

tpl_1 = [1, "ankur", "c"]
tpl_2 = [2.5, 7, 3.2]
tpl_3 = ([1,2,5],[3,0,9])
print(np.array(tpl_1))
print(np.array(tpl_2))
print(np.array(tpl_3))

[1 2 7 0 4 8]
['1' 'ankur' 'c']
[2.5 7.  3.2]
[[1 2 5]
 [3 0 9]]


In [13]:
# 12. Write a NumPy program to append values to the end of an array. 

x = np.array([1,7,8,4])
y = np.array([5,9,11])
print(x)
print(y)
z1 = np.append(x,y)
z2 = np.append(y,x)
print(z1)
print(z2)

[1 7 8 4]
[ 5  9 11]
[ 1  7  8  4  5  9 11]
[ 5  9 11  1  7  8  4]


In [14]:
# 13. Write a NumPy program to create an empty and a full array. 

x = np.empty((2,3))
print(x)
y = np.full((2,3),4)
print(y)

[[4.9e-324 9.9e-324 2.5e-323]
 [1.5e-323 0.0e+000 4.4e-323]]
[[4 4 4]
 [4 4 4]]


In [15]:
# 14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values 
# are stored into a NumPy array.

x = np.array([32,109,67])
print("Centigrade degrees: ", x, "degrees C")
y = (x * 1.8) + 32
print("Fahrenheit degrees: ", y, "degrees F")

Centigrade degrees:  [ 32 109  67] degrees C
Fahrenheit degrees:  [ 89.6 228.2 152.6] degrees F


In [16]:
# 15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers. 

x = np.array([1+2j])
print(x)
print(x.real)
print(x.imag)

y = np.array([[2+3j],[4+6j]])
print(y)
print(y.real)
print(y.imag)

[1.+2.j]
[1.]
[2.]
[[2.+3.j]
 [4.+6.j]]
[[2.]
 [4.]]
[[3.]
 [6.]]


In [17]:
# 16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes 
# and total bytes consumed by the elements. 

x = np.array([[2,5],[4,6]])
print(x)
print("Number of elements in the array:" , x.size)
print("Length of one array element:", x.itemsize, "bytes")
print("Total bytes consumed by the array elements", x.nbytes, "bytes")

[[2 5]
 [4 6]]
Number of elements in the array: 4
Length of one array element: 8 bytes
Total bytes consumed by the array elements 32 bytes


In [18]:
# 17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.in1d(x,y)) 

[1 9 5 4]
[5 1 7 2 4 8]
[ True False  True  True]


In [19]:
# 18. Write a NumPy program to find common values between two arrays. 

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.intersect1d(x,y))

[1 9 5 4]
[5 1 7 2 4 8]
[1 4 5]


In [20]:
# 19. Write a NumPy program to get the unique elements of an array.

x = np.array([1,9,5,4,9,1])
print(x)
print(np.unique(x))


y = np.array([[1,9,5],[4,9,1]])
print(y)
print(np.unique(y))

[1 9 5 4 9 1]
[1 4 5 9]
[[1 9 5]
 [4 9 1]]
[1 4 5 9]


In [21]:
# 20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, 
# unique values in array1 that are not in array2.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.setdiff1d(x,y)) #elements which are in x but not in y
print(np.setdiff1d(y,x)) #elements which are in y but not in x

[1 9 5 4]
[5 1 7 2 4 8]
[9]
[2 7 8]


In [22]:
# 21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, 
# unique values that are in only one (not both) of the input arrays.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.setxor1d(x,y)) 

[1 9 5 4]
[5 1 7 2 4 8]
[2 7 8 9]


In [24]:
# 22. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of 
# values that are in either of the two input arrays.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.union1d(x,y))

[1 9 5 4]
[5 1 7 2 4 8]
[1 2 4 5 7 8 9]


In [28]:
# 23. Write a NumPy program to test whether all elements in an array evaluate to True. 

print(np.all([[True,True],[False,True]]))
print(np.all([[True,True,True],[True,True,True]]))
print(np.all([0,1,2,3]))
print(np.all([1,1,2,3]))
#returns true if all values are true

False
True
False
True


In [33]:
# 24. Write a NumPy program to test whether any array element along a given axis evaluates to True.

print(np.any([[True,True],[False,True]]))
print(np.any([[True,True,True],[True,True,True]]))
print(np.any([0,1,2,3]))
print(np.any([1,1,2,3]))
print(np.any([0,0,0]))

True
True
True
True
False


In [41]:
# 25. Write a NumPy program to construct an array by repeating.

print(np.tile(3,2))   #repeats '3' 2 times
print(np.tile([[3,2],[1,0]], 3))   #repeats each array 3 times

[3 3]
[[3 2 3 2 3 2]
 [1 0 1 0 1 0]]


In [59]:
# 26. Write a NumPy program to repeat elements of an array.

print(np.repeat(3,2))   #repeats '3' 2 times
print(np.repeat([[3,2],[1,0]], 3))   #repeats each element 3 times and return a 1d array
print(np.repeat([[3,2],[1,0]], 2, axis = 1)) #repeats each element 2 times along axis = 1 that is columns
print(np.repeat([[3,2],[1,0]], 2, axis = 0)) #repeats each element 2 times along axis = 0 that is rows

#difference between np.repeat and tile:
#np.repeat repeats element of an array
#np.tile construct an array by repeating the array the number of times given. 

[3 3]
[3 3 3 2 2 2 1 1 1 0 0 0]
[[3 3 2 2]
 [1 1 0 0]]
[[3 2]
 [3 2]
 [1 0]
 [1 0]]


In [53]:
# 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
  
print(np.argmax([3,2,5,6,9]), np.argmin([3,2,5,6,9])) 
print(np.argmax([[3,2],[0,1]], axis = 1), np.argmin([[3,2],[0,1]], axis = 1)) 
print(np.argmax([[0,2],[1,3]], axis = 0), np.argmin([[0,2],[1,3]], axis = 0)) 

4 1
[0 1] [1 0]
[1 1] [0 0]


In [58]:
# 28. Write a NumPy program compare two given arrays.

x = np.array([1,9,5,4])
y = np.array([6,9,0,5])

print(np.equal(x,y))
print(np.greater(x,y))
print(np.less(x,y))
print(np.greater_equal(x,y))
print(np.less_equal(x,y))

[False  True False False]
[False False  True False]
[ True False False  True]
[False  True  True False]
[ True  True False  True]


In [72]:
# 29. Write a NumPy program to sort an along the first, last axis of an array. 

x = np.array([[1,9],[2,3]])
print(x)
print(np.sort(x, axis = 0))
print("*****")
y = np.array([[2,1],[3,5]])
print(y)
print(np.sort(y, axis = 1))
print("*****")
z = np.array([[1,9,3],[2,5,3]])
print(z)
print(np.sort(z, axis = 0))

[[1 9]
 [2 3]]
[[1 3]
 [2 9]]
*****
[[2 1]
 [3 5]]
[[1 2]
 [3 5]]
*****
[[1 9 3]
 [2 5 3]]
[[1 5 3]
 [2 9 3]]


In [89]:
# 30. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, 
# then by first name).

x_first = ("Alisha","Mayank","Meenu","Ajay")
x_last = ("Rastogi","Khanna","Garg","Garg")
x = np.lexsort((x_first, x_last))
# "Alisha Rastogi", "Mayank Khanna", "Meenu Garg", "Ajay Gupta" - Pairs of first and last names
# lexsort will first sort according to the last key, then second last and so on
print(x)

[3 2 1 0]


In [101]:
# 31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

x = np.array([[11,9,5,14],[1,3,18,91]])
print(x[x>10])
print(np.nonzero(x>10))

[11 14 18 91]
(array([0, 0, 1, 1]), array([0, 3, 2, 3]))


In [106]:
# 32. Write a NumPy program to save a NumPy array to a text file.

x = np.array([[1,2],[5,0]])
print(x)
np.savetxt('Array_to_text.txt', x)

[[1 2]
 [5 0]]


In [112]:
# 33. Write a NumPy program to find the memory size of a NumPy array.

x = np.array([[1,2],[5,0]])
print(x.nbytes)

y = np.array([1,2,3,4,5,6,7,8])
print(y.size * y.itemsize)

32
64


In [119]:
# 34. Write a NumPy program to create an array of ones and an array of zeros. 

x = np.zeros(4, dtype = np.int)
print(x)

y = np.ones((2,3), dtype = np.int)
print(y)

[0 0 0 0]
[[1 1 1]
 [1 1 1]]


In [131]:
# 35. Write a NumPy program to change the dimension of an array.

x = np.array([[2,3],[1,0]])
print(x)
print(x.reshape(4,1))

y = np.array([[1,2,3],[7,1,0]])
print(y)
print(y.shape)
y.shape = (3,2)
print(y)

[[2 3]
 [1 0]]
[[2]
 [3]
 [1]
 [0]]
[[1 2 3]
 [7 1 0]]
(2, 3)
[[1 2]
 [3 7]
 [1 0]]


In [132]:
# 36. Write a NumPy program to create a contiguous flattened array. 

x = np.array([[2,3],[1,0]])
print(x)
print(np.ravel(x))

[[2 3]
 [1 0]]
[2 3 1 0]


In [148]:
# 37. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), 
# also print the shape, type and data type of the array. 

x = np.array([[1,8,2],[0,4,3]], dtype = np.int32)
print(type(x))
print(np.shape(x))
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


In [150]:
# 38. Write a NumPy program to create a new shape to an array without changing its data. 

x = np.array([[1,4,9],[0,5,3]])
print(x)
print(x.reshape(3,2))

[[1 4 9]
 [0 5 3]]
[[1 4]
 [9 0]
 [5 3]]


In [158]:
# 39. Write a NumPy program to change the data type of an array. 

x = np.array([[1,4,9],[0,5,3]])
print(x)
print(x.dtype)
y = x.astype(np.float16)
print(y)
print(y.dtype)

[[1 4 9]
 [0 5 3]]
int64
[[1. 4. 9.]
 [0. 5. 3.]]
float16


In [162]:
# 40. Write a NumPy program to create a new array of 3*5, filled with 2.

x = np.ones((3,5), dtype = np.int16) * 2
print(x)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [ ]:
# 41. 