In [2]:
import numpy as np

In [8]:
# 1. Write a Python program to find the maximum and minimum value of a given flattened array. 

x = np.arange(4)
print(x)
print(x.min())
print(x.max())

y = np.arange(6).reshape((3,2))
print(y)
print(y.min())
print(y.max())

[0 1 2 3]
0
3
[[0 1]
 [2 3]
 [4 5]]
0
5


In [12]:
# 2. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

y = np.array([9,8,2,3,1,5]).reshape((3,2))
print(y)
print(y.min(axis=1))
print(y.max(axis=1))

[[9 8]
 [2 3]
 [1 5]]
[8 2 1]
[9 3 5]


In [13]:
# 3. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array 
# along the second axis.

y = np.array([9,8,2,3,1,5]).reshape((2,3))
print(y)
print(y.max(axis=1) - y.min(axis=1))

[[9 8 2]
 [3 1 5]]
[7 4]


In [14]:
# 4. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis. 

y = np.array([9,8,2,3,1,5]).reshape((2,3))
print(y)
print(np.percentile(y, 80, 1))

[[9 8 2]
 [3 1 5]]
[8.6 4.2]


In [16]:
# 5. Write a NumPy program to compute the median of flattened given array. 

y = np.arange(6).reshape((3,2))
print(y)
print(np.median(y))

[[0 1]
 [2 3]
 [4 5]]
2.5


In [ ]:
# 6. Write a NumPy program to compute the weighted of a given array. 

