In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to print the NumPy version in your system.

print(np.__version__)

1.17.2


In [5]:
# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

lst = [12.23, 13.32, 100, 36.32]
print(np.array(lst))

[ 12.23  13.32 100.    36.32]


In [7]:
# 3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
# 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [14]:
# 5. Write a NumPy program to create an array with values ranging from 12 to 38.

x = np.arange(12,39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [22]:
# 6. Write a NumPy program to reverse an array (first element becomes last).

x = np.array([1,2,0,9,6,4])
print(x)
print(x[::-1])

[1 2 0 9 6 4]
[4 6 9 0 2 1]


In [28]:
# 7. Write a NumPy program to convert an array to a float type.

x = np.array([18,25,10,19,61,14])
print(x)
print(x.astype('float32'))

[18 25 10 19 61 14]
[18. 25. 10. 19. 61. 14.]
[18 25 10 19 61 14]


In [40]:
# 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

x = np.ones(16).reshape(4,4)
print(x)
y = np.zeros(4).reshape(2,2)
print(y)
x[1:3,1:3] = y
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [42]:
# 9. Write a NumPy program to add a border (filled with 0's) around an existing array. 

x = np.ones(16).reshape(4,4)
print(x)
x = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [51]:
# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. 

x = np.zeros(64).reshape(8,8)
#print(x)
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
