In [1]:
import numpy as np

In [22]:
# 1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

print("Sum:", np.add(4.0,1.2))

print("Difference:", np.subtract(4.0,1.2))

print("Product:", np.multiply(4.0,1.2))

print("Division:", np.divide(4.0,1.2))

Sum: 5.2
Difference: 2.8
Product: 4.8
Division: 3.3333333333333335


In [18]:
# 2. Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations 
# of the inputs in base-2.

a = np.log(2e-25)
print(a)

b = np.log(21e-25)
print(b)

print(np.logaddexp(a,b))

print(np.logaddexp2(a,b))

-56.8714801442912
-54.52010488712772
-54.429133108921995
-54.261936791001034


In [25]:
# 3. Write a NumPy program to get true division of the element-wise array inputs.

x = np.array([1,9,8,3,2])
print(x)

#true division works with dividing element-wise array inputs by a number 
print("True division by 2:", np.true_divide(x,2))
print("True division by 5:", np.true_divide(x,2.5))

[1 9 8 3 2]
True division by 2: [0.5 4.5 4.  1.5 1. ]
True division by 5: [0.4 3.6 3.2 1.2 0.8]


In [27]:
# 4. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs. 

x = np.array([1,9,8,3,2])
print(x)

#floor division either gives the largest integer smaller than or equal to the division of inputs
print(np.floor_divide(x,2))
print(np.floor_divide(x,3))

[1 9 8 3 2]
[0 4 4 1 1]
[0 3 2 1 0]


In [29]:
# 5. Write a NumPy program to get the powers of an array values element-wise.

x = np.array([1,9,8,3,2])
print(x)

print(np.power(x,2))     #power 2
print(np.power(x,3))     #power 3

[1 9 8 3 2]
[ 1 81 64  9  4]
[  1 729 512  27   8]


In [30]:
# 6. Write a NumPy program to get the element-wise remainder of an array of division. 

x = np.array([1,9.2,8.5,1.3,2])
print(x)

print(np.remainder(x,2))     
print(np.remainder(x,3))     

[1.  9.2 8.5 1.3 2. ]
[1.  1.2 0.5 1.3 0. ]
[1.  0.2 2.5 1.3 2. ]


In [31]:
# 7. Write a NumPy program to calculate the absolute value element-wise. 

x = np.array([-1,9.2,-8.5,1.3,2])
print(x)

print(np.abs(x))

[-1.   9.2 -8.5  1.3  2. ]
[1.  9.2 8.5 1.3 2. ]


In [34]:
# 8. Write a NumPy program to round array elements to the given number of decimals. 

print(np.round([7.2,3.5,0.9]))                      #general rounding up
print(np.round([7.20,3.5672,0.9123], decimals=2))   #two two decimal places

[7. 4. 1.]
[7.2  3.57 0.91]
[7. 4. 1.]


In [35]:
# 9. Write a NumPy program to round elements of the array to the nearest integer. 

# rounding elements to the nearest integer
print(np.rint([7.2,3.5,0.9,6.1,110.3]))

[  7.   4.   1.   6. 110.]


In [38]:
# 10. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array. 

print(np.floor([7.2,3.5,0.9,6.1,110.3]))
print(np.ceil([7.2,3.5,0.9,6.1,110.3]))
print(np.trunc([7.2,3.5,0.9,6.1,110.3]))

[  7.   3.   0.   6. 110.]
[  8.   4.   1.   7. 111.]
[  7.   3.   0.   6. 110.]


In [41]:
# 11. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

x = np.arange(15).reshape((5,3))
print(x)

y = np.arange(6).reshape((3,2))
print(y)

print(np.dot(x,y))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [49]:
# 12. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of 
# complex numbers.

x = np.array([1+2j, 3-1j, 6+4j, 2-5j])
print(x)

y = np.array([6+1j, 4-2j, 1+1j, 2-7j])
print(y)

print(np.dot(x,y))

[1.+2.j 3.-1.j 6.+4.j 2.-5.j]
[6.+1.j 4.-2.j 1.+1.j 2.-7.j]
(-15-11j)


In [51]:
# 13. Write a NumPy program to create an inner product of two arrays. 

x = np.arange(6).reshape((3,2))
print(x)

y = np.arange(6).reshape((3,2))
print(y)

print(np.inner(x,y))

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]


In [59]:
# 14. Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.

x = np.array([2,9,1])
print(x)

y = np.array([7,1,3])
print(y)

print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

[2 9 1]
[7 1 3]
26
[[14  2  6]
 [63  9 27]
 [ 7  1  3]]
[ 26   1 -61]


In [61]:
# 15. Write a NumPy program to generate a matrix product of two arrays.

x = np.array([2,9,1])
print(x)

y = np.array([7,1,3])
print(y)

print(np.matmul(x,y))
print(np.dot(x,y))  #both np.dot a

[2 9 1]
[7 1 3]
26
26
