In [1]:
import numpy as np

In [10]:
# 1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

x = np.array([[11,4],[7,10]]).reshape(2,2)
print(x)

print(np.sort(x, axis=0))
print(np.sort(x, axis=1))
print(np.sort(x, axis=None))   #flattened array

[[11  4]
 [ 7 10]]
[[ 7  4]
 [11 10]]
[[ 4 11]
 [ 7 10]]
[[ 4 11]
 [ 7 10]]


In [14]:
# 2. Write a NumPy program to create a structured array from given student name, height, class and their data types. 
# Now sort the array on height.

data_type = [('name','U25'),('height', 'float'),('class','int')]
students_info = [('Kate', 60.2, 10), ('James', 56.4, 8), ('Laural', 61.5, 11), ('Ana', 59.1, 8)]

#creating structured array
students = np.array(students_info, dtype=data_type)
print(students)

print(np.sort(students, order='height'))

[('Kate', 60.2, 10) ('James', 56.4,  8) ('Laural', 61.5, 11)
 ('Ana', 59.1,  8)]
[('James', 56.4,  8) ('Ana', 59.1,  8) ('Kate', 60.2, 10)
 ('Laural', 61.5, 11)]


In [16]:
# 3. Write a NumPy program to create a structured array from given student name, height, class and their data 
# types. Now sort by class, then height if class are equal. 

data_type = [('name','U25'),('height', 'float'),('class','int')]
students_info = [('Kate', 60.2, 10), ('James', 56.4, 8), ('Laural', 61.5, 11), ('Ana', 59.1, 8)]

#creating structured array
students = np.array(students_info, dtype=data_type)
print(students)

print(np.sort(students, order=['class','height']))

[('Kate', 60.2, 10) ('James', 56.4,  8) ('Laural', 61.5, 11)
 ('Ana', 59.1,  8)]
[('James', 56.4,  8) ('Ana', 59.1,  8) ('Kate', 60.2, 10)
 ('Laural', 61.5, 11)]


In [20]:
# 4. Write a NumPy program to sort the student id with increasing height of the students from given students id 
# and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40.5, 42.2, 45.1, 41.8, 38.5, 40.2, 42.0])

#to print the indices of the sort order by multiple columns, first by student_height and then by student_id
indices = np.lexsort((student_id, student_height))
print(indices)

for n in indices:
    print(student_id[n], student_height[n])

[4 5 0 3 6 1 2]
1682 38.5
5241 40.2
1023 40.5
1671 41.8
4532 42.0
5202 42.2
6230 45.1


In [25]:
# 5. Write a NumPy program to get the indices of the sorted elements of a given array. 

x = np.array([1,7,9,2,35,8,7,11])
print(x)

print(np.argsort(x))

[ 1  7  9  2 35  8  7 11]
[0 3 1 6 5 2 7 4]


In [26]:
# 6. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.

complex_number = [3 + 1j, 1 - 2j, 8 - 9j, 4 - 5j, 3 + 0j]

print(np.sort_complex(complex_number))

[1.-2.j 3.+0.j 3.+1.j 4.-5.j 8.-9.j]


In [29]:
# 7. Write a NumPy program to partition a given array in a specified position and move all the smaller elements 
# values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random 
# choice).

num_array = [1, 9, 5, 8, 10, 5, 0, 6, 3, 14]

#partitioning the array with numbers less than 6 on the left and more than 6 on the right
print(np.partition(num_array, 6)) 
print(np.partition(num_array, 4))
print(np.partition(num_array, 10))

[ 5  3  5  1  0  6  8  9 10 14]
[ 1  0  3  5  5  6  9  8 10 14]


In [37]:
# 8. Write a NumPy program to sort the specified number of elements from beginning of a given array.

x = np.random.rand(15)
print(x)

#return the indices of sorted array by sorting only the elements from 0 to 3
print(np.argpartition(x,range(4))) 
print(x[np.argpartition(x,range(4))])

[0.62702751 0.58949728 0.25835295 0.75880769 0.82472308 0.15861528
 0.40743769 0.82094972 0.82991147 0.64726998 0.47457611 0.88783957
 0.31258405 0.46070325 0.81895787]
[ 5  2 12  6 13  0  3  7  8  9 10 11  1  4 14]
[0.15861528 0.25835295 0.31258405 0.40743769 0.46070325 0.62702751
 0.75880769 0.82094972 0.82991147 0.64726998 0.47457611 0.88783957
 0.58949728 0.82472308 0.81895787]
