In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to concatenate element-wise two arrays of string. 

x = np.array(['Tom', 'Male'], dtype = np.str)
print(x)

y = np.array([' Gina', ' Female'], dtype = np.str)
print(y)

print(np.char.add(x,y))

['Tom' 'Male']
[' Gina' ' Female']
['Tom Gina' 'Male Female']


In [3]:
# 2. Write a NumPy program to repeat all the elements three times of a given array of string. 

x = np.array(['Tom', 'Male'], dtype = np.str)
print(x)

print(np.char.multiply(x, 3))

['Tom' 'Male']
['TomTomTom' 'MaleMaleMale']


In [4]:
# 3. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the 
# elements of a given array.

x = np.array(['Tom', 'male', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

print(np.char.capitalize(x))
print(np.char.lower(x))
print(np.char.upper(x))
print(np.char.swapcase(x))
print(np.char.title(x))

['Tom' 'male' 'GRADUATE STUDENT']
['Tom' 'Male' 'Graduate student']
['tom' 'male' 'graduate student']
['TOM' 'MALE' 'GRADUATE STUDENT']
['tOM' 'MALE' 'graduate student']
['Tom' 'Male' 'Graduate Student']


In [5]:
# 4. Write a NumPy program to make the length of each element 15 of a given array and the string centered / 
# left-justified / right-justified with paddings of _. 

x = np.array(['Tom', 'male', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

print(np.char.center(x, 15, fillchar = '_'))
print(np.char.ljust(x, 15, fillchar = '_'))
print(np.char.rjust(x, 15, fillchar = '_'))

['Tom' 'male' 'GRADUATE STUDENT']
['______Tom______' '______male_____' 'GRADUATE STUDEN']
['Tom____________' 'male___________' 'GRADUATE STUDEN']
['____________Tom' '___________male' 'GRADUATE STUDEN']


In [6]:
# 5. Write a NumPy program to insert a space between characters of all the elements of a given array.

x = np.array(['Tom', 'male', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

print(np.char.join(" ", x))

['Tom' 'male' 'GRADUATE STUDENT']
['T o m' 'm a l e' 'G R A D U A T E   S T U D E N T']


In [7]:
# 6. Write a NumPy program to encode all the elements of a given array in cp500 and decode it again.

x = np.array(['Tom', 'male', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

y = np.char.encode(x, 'cp500')
print(y)

print(np.char.decode(y, 'cp500'))

['Tom' 'male' 'GRADUATE STUDENT']
[b'\xe3\x96\x94' b'\x94\x81\x93\x85'
 b'\xc7\xd9\xc1\xc4\xe4\xc1\xe3\xc5@\xe2\xe3\xe4\xc4\xc5\xd5\xe3']
['Tom' 'male' 'GRADUATE STUDENT']


In [8]:
# 7. Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array. 

x = np.array(['Tom      ', '      male', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

print(np.char.strip(x))

['Tom      ' '      male' 'GRADUATE STUDENT']
['Tom' 'male' 'GRADUATE STUDENT']


In [9]:
# 8. Write a NumPy program to remove the leading whitespaces of all the elements of a given array.

x = np.array(['Tom      ', '      male', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

print(np.char.lstrip(x))

['Tom      ' '      male' 'GRADUATE STUDENT']
['Tom      ' 'male' 'GRADUATE STUDENT']


In [10]:
# 9. Write a NumPy program to remove the trailing whitespaces of all the elements of a given array. 

x = np.array(['Tom      ', 'male', 'GRADUATE STUDENT          '], dtype = np.str)
print(x)

print(np.char.rstrip(x))

['Tom      ' 'male' 'GRADUATE STUDENT          ']
['Tom' 'male' 'GRADUATE STUDENT']


In [11]:
# 10. Write a NumPy program to split the element of a given array with spaces.

x = np.array(['Tom Amy', 'male female', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

print(np.char.split(x))

['Tom Amy' 'male female' 'GRADUATE STUDENT']
[list(['Tom', 'Amy']) list(['male', 'female'])
 list(['GRADUATE', 'STUDENT'])]


In [12]:
# 11. Write a NumPy program to split the element of a given array to multiple lines. 

x = np.array(['Tom\Amy', 'male female', 'GRADUATE STUDENT'], dtype = np.str)
print(x)

print(np.char.splitlines(x))

['Tom\\Amy' 'male female' 'GRADUATE STUDENT']
[list(['Tom\\Amy']) list(['male female']) list(['GRADUATE STUDENT'])]


In [13]:
# 12. Write a NumPy program to make all the elements of a given string to a numeric string of 5 digits with zeros 
# on its left.

x = np.array(['567', '81912', '91'])
print(x)

print(np.char.zfill(x, 5))

['567' '81912' '91']
['00567' '81912' '00091']


In [14]:
# 13. Write a NumPy program to replace "PHP" with "Python" in the element of a given array. 

x = np.array(['PHP', 'Java', 'C++'])
print(x)

print(np.char.replace(x, 'PHP', 'Python'))

['PHP' 'Java' 'C++']
['Python' 'Java' 'C++']


In [15]:
# 14. Write a NumPy program to test equal, not equal, greater equal, greater and less test of all the elements of two 
# given arrays. 

a = np.array(['Tom', 'Male', 'America'], dtype = np.str)
print(a)

b = np.array(['Tom', 'Male', 'America'], dtype = np.str)
print(b)

c = np.array(['tom', 'male', 'america'], dtype = np.str)
print(c)

d = np.array(['tom  ', '   male', 'argentina'], dtype = np.str)
print(d)

print("******")
print("Test Equal")
print(np.char.equal(a,b))
print(np.char.equal(a,c))
print(np.char.equal(a,d))
print(np.char.equal(c,d))

print("******")
print("Test Not Equal")
print(np.char.not_equal(a,b))
print(np.char.not_equal(a,c))
print(np.char.not_equal(a,d))
print(np.char.not_equal(c,d))

print("******")
print("Test Less Equal")
print(np.char.less_equal(a,b))
print(np.char.less_equal(a,c))
print(np.char.less_equal(a,d))
print(np.char.less_equal(c,d))

print("******")
print("Test Greater Equal")
#This comparison is performed by first stripping whitespace characters from the end of the string.
#Return (x1 >= x2) element-wise.
print(np.char.greater_equal(a,b))
print(np.char.greater_equal(a,c))
print(np.char.greater_equal(a,d))
print(np.char.greater_equal(c,d))

print("******")
print("Test Less")
print(np.char.less(a,b))
print(np.char.less(a,c))
print(np.char.less(a,d))
print(np.char.less(c,d))

print("******")
print("Test Greater")
print(np.char.greater(a,b))
print(np.char.greater(a,c))
print(np.char.greater(a,d))
print(np.char.greater(c,d))

['Tom' 'Male' 'America']
['Tom' 'Male' 'America']
['tom' 'male' 'america']
['tom  ' '   male' 'argentina']
******
Test Equal
[ True  True  True]
[False False False]
[False False False]
[ True False False]
******
Test Not Equal
[False False False]
[ True  True  True]
[ True  True  True]
[False  True  True]
******
Test Less Equal
[ True  True  True]
[ True  True  True]
[ True False  True]
[ True False  True]
******
Test Greater Equal
[ True  True  True]
[False False False]
[False  True False]
[ True  True False]
******
Test Less
[False False False]
[ True  True  True]
[ True False  True]
[False False  True]
******
Test Greater
[False False False]
[False False False]
[False  True False]
[False  True False]


In [16]:
# 15. Write a NumPy program to count the number of "P" in a given array, element-wise.

a = np.array(['PHP', 'Python', 'C++', 'Java'], dtype = np.str)
print(a)

print(np.char.count(a, 'p'))
print(np.char.count(a, 'P'))

['PHP' 'Python' 'C++' 'Java']
[0 0 0 0]
[2 1 0 0]


In [17]:
# 16. Write a NumPy program to count the lowest index of "P" in a given array, element-wise. 

a = np.array(['PHP', 'Python', 'C++', 'Java', 'EXAMPLE'], dtype = np.str)
print(a)

#Lowest index of "P" in "PHP" is 0, in C++ is -1 as it is not there
print(np.char.find(a, 'P'))

['PHP' 'Python' 'C++' 'Java' 'EXAMPLE']
[ 0  0 -1 -1  4]


In [18]:
# 17. Write a NumPy program to check whether each element of a given array is composed of digits only, lower case 
# letters only and upper case letters only. 

a = np.array(['Tom', 'Male', 'America'], dtype = np.str)
print(a)

b = np.array(['tom', 'male', 'america'], dtype = np.str)
print(b)

c = np.array(['1235', '3546', '0192'], dtype = np.str)
print(c)

d = np.array(['1235', 'Alpha', '0192'], dtype = np.str)
print(d)

e = np.array(['tom', 'MALE', 'america'], dtype = np.str)
print(e)

print("Is Digit?")
print(np.char.isdigit(a))
print(np.char.isdigit(b))
print(np.char.isdigit(c))
print(np.char.isdigit(d))
print(np.char.isdigit(e))

print("Is Lower?")
print(np.char.islower(a))
print(np.char.islower(b))
print(np.char.islower(c))
print(np.char.islower(d))
print(np.char.islower(e))

print("Is Upper?")
print(np.char.isupper(a))
print(np.char.isupper(b))
print(np.char.isupper(c))
print(np.char.isupper(d))
print(np.char.isupper(e))

['Tom' 'Male' 'America']
['tom' 'male' 'america']
['1235' '3546' '0192']
['1235' 'Alpha' '0192']
['tom' 'MALE' 'america']
Is Digit?
[False False False]
[False False False]
[ True  True  True]
[ True False  True]
[False False False]
Is Lower?
[False False False]
[ True  True  True]
[False False False]
[False False False]
[ True False  True]
Is Upper?
[False False False]
[False False False]
[False False False]
[False False False]
[False  True False]


In [19]:
# 18. Write a NumPy program to check whether each element of a given array starts with "P".

a = np.array(['PHP', 'Python', 'C++', 'Java', 'EXAMPLE'], dtype = np.str)
print(a)

print(np.char.startswith(a,'P'))

['PHP' 'Python' 'C++' 'Java' 'EXAMPLE']
[ True  True False False False]
