In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to compute the multiplication of two given matrixes. 

x = [[1,2],[3,4]]
y = [[0,4],[3,6]]
print(x)
print(y)
print(np.dot(x,y))

[[1, 2], [3, 4]]
[[0, 4], [3, 6]]
[[ 6 16]
 [12 36]]


In [3]:
# 2. Write a NumPy program to compute the outer product of two given vectors.

x = [[1,2],[3,4]]
y = [[0,4],[3,6]]
print(np.outer(x,y))

[[ 0  4  3  6]
 [ 0  8  6 12]
 [ 0 12  9 18]
 [ 0 16 12 24]]


In [4]:
# 3. Write a NumPy program to compute the cross product of two given vectors.

x = [[1,2],[3,4]]
y = [[0,4],[3,6]]
print(np.cross(x,y))
print(np.cross(y,x))

[4 6]
[-4 -6]


In [5]:
# 4. Write a NumPy program to compute the determinant of a given square array. 

from numpy import linalg

x = [[1,2],[3,4]]
print(np.linalg.det(x))

-2.0000000000000004


In [6]:
# 5. Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays. 

x = [1,2,5,7]
y = [3,6,0,1]
print(np.einsum('n,n', x,y))

a = [[1,2],[3,4]]
b = [[0,4],[3,6]]
print(np.einsum('nk,nk', a,b))

22
41


In [7]:
# 6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and 
# in higher dimension.

x = [1,2,5,7]
y = [3,6,0,1]
print(np.inner(x,y))

a = [[1,2],[3,4]]
b = [[0,4],[3,6]]
print(np.inner(a,b))

22
[[ 8 15]
 [16 33]]


In [8]:
# 7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array. 

x = [[1,2],[3,4]]
print(np.linalg.eig(x))

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [9]:
# 8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.

x = [1,2,5,7]
y = [3,6,0,1]
print(np.kron(x,y))

a = [[1,2],[3,4]]
b = [[0,4],[3,6]]
print(np.kron(a,b))

[ 3  6  0  1  6 12  0  2 15 30  0  5 21 42  0  7]
[[ 0  4  0  8]
 [ 3  6  6 12]
 [ 0 12  0 16]
 [ 9 18 12 24]]


In [10]:
# 9. Write a NumPy program to compute the condition number of a given matrix.

x = [[1,2],[3,4]]
print(np.linalg.cond(x))

14.933034373659265


In [11]:
# 10. Write a NumPy program to find a matrix or vector norm.

x = [1,2,5,7]
print("Vector norm:", np.linalg.norm(x))

a = [[1,2],[3,4]]
print("Matrix norm:", np.linalg.norm(a))

Vector norm: 8.888194417315589
Matrix norm: 5.477225575051661


In [12]:
# 11. Write a NumPy program to compute the determinant of an array. 

x = [[1,2],[3,4]]
print(np.linalg.det(x))

-2.0000000000000004


In [13]:
# 12. Write a NumPy program to compute the inverse of a given matrix.

x = [[1,2],[3,4]]
print(np.linalg.inv(x))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
# 13. Write a NumPy program to calculate the QR decomposition of a given matrix. 

x = [[1,2],[3,4]]
q, r = np.linalg.qr(x)
print( "q =\n", q, "\nr =\n", r)

q =
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]] 
r =
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [15]:
# 14. Write a NumPy program to compute the condition number of a given matrix.

x = [[1,2],[3,4]]
print(np.linalg.cond(x))

14.933034373659265


In [16]:
# 15. Write a NumPy program to compute the sum of the diagonal element of a given array.

x = [[1,2],[3,4]]
print(np.trace(x))

y = [[1,2,2],[3,4,0],[7,9,8]]
print(np.trace(y))

5
13


In [17]:
# 16. Write a NumPy program to get the lower-triangular L in the Cholesky decomposition of a given array.

a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)
print(np.linalg.cholesky(a))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -5.  3.]]


In [18]:
# 17. Write a NumPy program to get the qr factorization of a given array. 

x = [[1,2],[3,4]]
q, r = np.linalg.qr(x)
print( "q =\n", q, "\nr =\n", r)

q =
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]] 
r =
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [19]:
# 18. Write a NumPy program to compute the factor of a given array by Singular Value Decomposition.

x = [[1,2],[3,4]]
U, s, V = np.linalg.svd(a, full_matrices=False)
print("U =\n", U, "\ns =\n", s, "\nV =\n", V)

U =
 [[-0.15366711 -0.34436858  0.92617315]
 [-0.49718558 -0.78306599 -0.37364979]
 [ 0.85392794 -0.51789761 -0.0508836 ]] 
s =
 [1.31737635e+02 7.22453921e+00 3.78253090e-02] 
V =
 [[-0.15366711 -0.49718558  0.85392794]
 [-0.34436858 -0.78306599 -0.51789761]
 [ 0.92617315 -0.37364979 -0.0508836 ]]


In [20]:
# 19. Write a NumPy program to calculate the Frobenius norm and the condition number of a given array.

x = [[1,2],[3,4]]
print(np.linalg.norm(x, 'fro'))
print(np.linalg.cond(x))

5.477225575051661
14.933034373659265
