In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to get the numpy version and show numpy build configuration.
print("NumPy version: ", np.__version__)
print("NumPy configuration: ", np.__config__.show())

NumPy version:  1.17.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ankurrastogi/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ankurrastogi/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ankurrastogi/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ankurrastogi/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ankurrastogi/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ankurrastogi/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/ankurrastogi/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/ankurrastogi/opt/anaconda3/inc

In [3]:
# 2. Write a NumPy program to  get help on the add function. 
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

In [4]:
# 3. Write a NumPy program to test whether none of the elements of a given array is zero. 

x = np.array([1,2,3,4])
print("Given array:")
print(x)
print(np.all(x))

y = np.array([1,2,0,9])
print("Given array:")
print(y)
print(np.all(y))

z = np.array([0,0,0,0])
print("Given array:")
print(z)
print(np.all(z))

Given array:
[1 2 3 4]
True
Given array:
[1 2 0 9]
False
Given array:
[0 0 0 0]
False


In [5]:
# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

x = np.array([1,2,3,4])
print("Given array:")
print(x)
print(np.any(x))

y = np.array([1,2,0,9])
print("Given array:")
print(y)
print(np.any(y))

z = np.array([0,0,0,0])
print("Given array:")
print(z)
print(np.any(z))

Given array:
[1 2 3 4]
True
Given array:
[1 2 0 9]
True
Given array:
[0 0 0 0]
False


In [6]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

x = np.array([1,2,3,4])
print("Given array:")
print(x)
print(np.isinf(x))
print(np.isnan(x))

y = np.array([1,np.nan,3,4])
print("Given array:")
print(y)
print(np.isinf(y))
print(np.isnan(y))

z = np.array([1,np.nan,3,np.inf])
print("Given array:")
print(z)
print(np.isinf(z))
print(np.isnan(z))

Given array:
[1 2 3 4]
[False False False False]
[False False False False]
Given array:
[ 1. nan  3.  4.]
[False False False False]
[False  True False False]
Given array:
[ 1. nan  3. inf]
[False False False  True]
[False  True False False]


In [7]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity. 

x = np.array([1,2,3,4])
print("Given array:")
print(x)
print(np.isinf(x))

y = np.array([1,np.nan,3,4])
print("Given array:")
print(y)
print(np.isinf(y))

z = np.array([1,np.nan,3,np.inf])
print("Given array:")
print(z)
print(np.isinf(z))

Given array:
[1 2 3 4]
[False False False False]
Given array:
[ 1. nan  3.  4.]
[False False False False]
Given array:
[ 1. nan  3. inf]
[False False False  True]


In [8]:
# 7. Write a NumPy program to test element-wise for NaN of a given array.

x = np.array([1,2,3,4])
print("Given array:")
print(x)
print(np.isnan(x))

y = np.array([1,np.nan,3,4])
print("Given array:")
print(y)
print(np.isnan(y))

z = np.array([1,np.nan,3,np.inf])
print("Given array:")
print(z)
print(np.isnan(z))

Given array:
[1 2 3 4]
[False False False False]
Given array:
[ 1. nan  3.  4.]
[False  True False False]
Given array:
[ 1. nan  3. inf]
[False  True False False]


In [9]:
# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. 
# Also test whether a given number is a scalar type or not.

x = np.array([1, 3 + 1j])
print("Given number:")
print(x)
print("Complex: ", np.iscomplex(x))
print("Real: ", np.isreal(x))

y = np.array([2,1.5])
print("Given number:")
print(y)
print("Complex: ", np.iscomplex(y))
print("Real: ", np.isreal(y))

print(np.isscalar(2.5))
print(np.isscalar([1]))
print(np.isscalar(1 + 5j))

Given number:
[1.+0.j 3.+1.j]
Complex:  [False  True]
Real:  [ True False]
Given number:
[2.  1.5]
Complex:  [False False]
Real:  [ True  True]
True
False
True


In [10]:
# 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance. 

x = [5.00067e+05, 6.001e+08]
y = [5.00067e+04, 6.001e+08]

p = [1e10,1e-8]
q = [1e10,1e-9]

l = [1e10,1e-4]
m = [1e10,1e-5]

print("x and y are element-wise equal within a tolerance: ", np.allclose(x,y))
print("p and q are element-wise equal within a tolerance: ", np.allclose(p,q))
print("l and m are element-wise equal within a tolerance: ", np.allclose(l,m))

x and y are element-wise equal within a tolerance:  False
p and q are element-wise equal within a tolerance:  True
l and m are element-wise equal within a tolerance:  False


In [11]:
# 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) 
# of two given arrays.

a = [1,2]
b = [1,2]
c = [3,5]

print("Equal a and b: ", np.equal(a,b))
print("Equal b and c: ", np.equal(b,c))
print("Equal c and a: ", np.equal(c,a))
print("********")

print("a > b: ", np.greater(a,b))
print("b > c: ", np.greater(b,c))
print("c > a: ", np.greater(c,a))
print("********")

print("a < b: ", np.less(a,b))
print("b < c: ", np.less(b,c))
print("c < a: ", np.less(c,a))
print("********")

print("a >= b: ", np.greater_equal(a,b))
print("b >= c: ", np.greater_equal(b,c))
print("c >= a: ", np.greater_equal(c,a))
print("********")

print("a <= b: ", np.less_equal(a,b))
print("b <= c: ", np.less_equal(b,c))
print("c <= a: ", np.less_equal(c,a))

Equal a and b:  [ True  True]
Equal b and c:  [False False]
Equal c and a:  [False False]
********
a > b:  [False False]
b > c:  [False False]
c > a:  [ True  True]
********
a < b:  [False False]
b < c:  [ True  True]
c < a:  [False False]
********
a >= b:  [ True  True]
b >= c:  [False False]
c >= a:  [ True  True]
********
a <= b:  [ True  True]
b <= c:  [ True  True]
c <= a:  [False False]


In [12]:
# 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) 
# of two given arrays.

x = [5.00067e+05, 6.001e+08]
y = [5.00067e+04, 6.001e+08]

p = [1e10,1e-8]
q = [1e10,1e-9]

l = [1e10,1e-4]
m = [1e10,1e-5]

print("x and y are element-wise equal: ", np.equal(x,y))
print("x and y are element-wise equal within a tolerance: ", np.allclose(x,y))
print("**********")

print("p and q are element-wise equal: ", np.equal(p,q))
print("p and q are element-wise equal within a tolerance: ", np.allclose(p,q))
print("**********")

print("l and m are element-wise equal: ", np.equal(l,m))
print("l and m are element-wise equal within a tolerance: ", np.allclose(l,m))
print("**********")

x and y are element-wise equal:  [False  True]
x and y are element-wise equal within a tolerance:  False
**********
p and q are element-wise equal:  [ True False]
p and q are element-wise equal within a tolerance:  True
**********
l and m are element-wise equal:  [ True False]
l and m are element-wise equal within a tolerance:  False
**********


In [13]:
# 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of 
# the memory occupied by the array.

x = np.array([1,7,13,105])
# Method 1:
print("Memory occupied: %d bytes" % x.nbytes)
# Method 2:
print("Memory occupied: %d bytes" % (x.size * x.itemsize))

Memory occupied: 32 bytes
Memory occupied: 32 bytes


In [14]:
# 13. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

x = np.zeros(10)
print("Array with 10 zeros: ", x)

y = np.ones(10)
print("Array with 10 ones: ", y)

z = np.ones(10) * 5
print("Array with 10 fives: ", z)

Array with 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array with 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array with 10 fives:  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [15]:
# 14. Write a NumPy program to create an array of the integers from 30 to 70.

x = np.arange(30,71)
print(x)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [16]:
# 15. Write a NumPy program to create an array of all the even integers from 30 to 70. 

x = np.arange(30,71,2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [17]:
# 16. Write a NumPy program to create a 3x3 identity matrix. 

x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# 17. Write a NumPy program to generate a random number between 0 and 1.

#Method 1: 
x = np.random.random(1)
print(x)

#Method 2:
y = np.random.normal(0,1,1)
print(y)

[0.5873611]
[2.49815981]


In [19]:
# 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

x = np.random.normal(0,1,15)
print(x)

[ 0.55999197 -0.49040439  0.48139359  0.21187518  0.10704351  0.05349937
 -2.32317064  0.35439173 -0.00388012  1.24502303 -0.08694947  0.48023421
 -0.03410056  0.11591695  1.67700721]


In [20]:
# 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except 
# the first and last.

x = np.arange(15,55)
print("Vector:")
print(x)

print("Vector with values except first and last:")
print(x[1:-1])

Vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
Vector with values except first and last:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [21]:
# 20. Write a NumPy program to create a 3X4 array using and iterate over it.

x = np.arange(12).reshape(3,4) # Creating an array with 12 numbers and then converting it to a 3*4 matrix
print(x)

for i in np.nditer(x):
    print(i, end = " ") # end = " " to print in a single row separated by space

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11 

In [24]:
# 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50. 

x = np.linspace(6,49,10)
print(x)

[ 6.         10.77777778 15.55555556 20.33333333 25.11111111 29.88888889
 34.66666667 39.44444444 44.22222222 49.        ]


In [39]:
# 22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in 
# the range from 9 to 15.

x = np.arange(20)
print(list(x[0:9]) + list(-x[9:16]) + list(x[16:21]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, -9, -10, -11, -12, -13, -14, -15, 16, 17, 18, 19]


In [43]:
# 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10. 

x = np.random.randint(0,11,5)
print(x)

[ 4 10  7 10  1]


In [51]:
# 24. Write a NumPy program to multiply the values of two given vectors.

x = np.arange(5)
y = np.arange(5)
print(x)
print(y)
print("Product: ", x*y)

a = np.array([17,5,6,2])
b = np.random.randint(10,26,4)
print(a)
print(b)
print("Product: ", a*b)

[0 1 2 3 4]
[0 1 2 3 4]
Product:  [ 0  1  4  9 16]
[17  5  6  2]
[22 23 12 14]
Product:  [374 115  72  28]


In [54]:
# 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

x = np.arange(10,22).reshape(3,4)
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [61]:
# 26. Write a NumPy program to find the number of rows and columns of a given matrix.

x = np.arange(10,22).reshape(3,4)
print("Number of rows and columns: ", x.shape)
print("Number of columns: ", np.size(x,1))
print("Number of rows: ", np.size(x,0))

Number of rows and columns:  (3, 4)
Number of columns:  4
Number of rows:  3


In [65]:
# 27. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0. 

# Method 1:
x = np.identity(3)
print(x)

# Method 2:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
# 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, 
# and inside 0.

x = np.ones(100).reshape(10,10)
#print(x)
y = np.zeros(64).reshape(8,8)
#print(y)
x[1:-1,1:-1] = y
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [75]:
# 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

#Method 1:
x = np.zeros(25).reshape(5,5)
#print(x)
x[0,0] = 1
x[1,1] = 2
x[2,2] = 3
x[3,3] = 4
x[4,4] = 5
print(x)

#Method 2:
y = np.diag([1,2,3,4,5])
print(y)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [94]:
# 30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. 

x = np.zeros(16).reshape(4,4)
#print(x)
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
