In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to print the NumPy version in your system.

print(np.__version__)

1.17.2


In [5]:
# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

lst = [12.23, 13.32, 100, 36.32]
print(np.array(lst))

[ 12.23  13.32 100.    36.32]


In [7]:
# 3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
# 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [14]:
# 5. Write a NumPy program to create an array with values ranging from 12 to 38.

x = np.arange(12,39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [22]:
# 6. Write a NumPy program to reverse an array (first element becomes last).

x = np.array([1,2,0,9,6,4])
print(x)
print(x[::-1])

[1 2 0 9 6 4]
[4 6 9 0 2 1]


In [28]:
# 7. Write a NumPy program to convert an array to a float type.

x = np.array([18,25,10,19,61,14])
print(x)
print(x.astype('float32'))

[18 25 10 19 61 14]
[18. 25. 10. 19. 61. 14.]
[18 25 10 19 61 14]


In [40]:
# 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

x = np.ones(16).reshape(4,4)
print(x)
y = np.zeros(4).reshape(2,2)
print(y)
x[1:3,1:3] = y
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [42]:
# 9. Write a NumPy program to add a border (filled with 0's) around an existing array. 

x = np.ones(16).reshape(4,4)
print(x)
x = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [51]:
# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. 

x = np.zeros(64).reshape(8,8)
#print(x)
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [56]:
# 11. Write a NumPy program to convert a list and tuple into arrays.

lst = [1,2,7,0,4,8]
print(np.array(lst))
#print(np.asarray(lst)) 

tpl_1 = [1, "ankur", "c"]
tpl_2 = [2.5, 7, 3.2]
tpl_3 = ([1,2,5],[3,0,9])
print(np.array(tpl_1))
print(np.array(tpl_2))
print(np.array(tpl_3))

[1 2 7 0 4 8]
['1' 'ankur' 'c']
[2.5 7.  3.2]
[[1 2 5]
 [3 0 9]]


In [60]:
# 12. Write a NumPy program to append values to the end of an array. 

x = np.array([1,7,8,4])
y = np.array([5,9,11])
print(x)
print(y)
z1 = np.append(x,y)
z2 = np.append(y,x)
print(z1)
print(z2)

[1 7 8 4]
[ 5  9 11]
[ 1  7  8  4  5  9 11]
[ 5  9 11  1  7  8  4]


In [65]:
# 13. Write a NumPy program to create an empty and a full array. 

x = np.empty((2,3))
print(x)
y = np.full((2,3),4)
print(y)

[[4.9e-324 9.9e-324 2.5e-323]
 [1.5e-323 0.0e+000 4.4e-323]]
[[4 4 4]
 [4 4 4]]


In [69]:
# 14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values 
# are stored into a NumPy array.

x = np.array([32,109,67])
print("Centigrade degrees: ", x, "degrees C")
y = (x * 1.8) + 32
print("Fahrenheit degrees: ", y, "degrees F")

Centigrade degrees:  [ 32 109  67] degrees C
Fahrenheit degrees:  [ 89.6 228.2 152.6] degrees F


In [72]:
# 15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers. 

x = np.array([1+2j])
print(x)
print(x.real)
print(x.imag)

y = np.array([[2+3j],[4+6j]])
print(y)
print(y.real)
print(y.imag)

[1.+2.j]
[1.]
[2.]
[[2.+3.j]
 [4.+6.j]]
[[2.]
 [4.]]
[[3.]
 [6.]]


In [79]:
# 16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes 
# and total bytes consumed by the elements. 

x = np.array([[2,5],[4,6]])
print(x)
print("Number of elements in the array:" , x.size)
print("Length of one array element:", x.itemsize, "bytes")
print("Total bytes consumed by the array elements", x.nbytes, "bytes")

[[2 5]
 [4 6]]
Number of elements in the array: 4
Length of one array element: 8 bytes
Total bytes consumed by the array elements 32 bytes


In [87]:
# 17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.in1d(x,y)) 

[1 9 5 4]
[5 1 7 2 4 8]
[ True False  True  True]


In [89]:
# 18. Write a NumPy program to find common values between two arrays. 

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.intersect1d(x,y))

[1 9 5 4]
[5 1 7 2 4 8]
[1 4 5]


In [94]:
# 19. Write a NumPy program to get the unique elements of an array.

x = np.array([1,9,5,4,9,1])
print(x)
print(np.unique(x))


y = np.array([[1,9,5],[4,9,1]])
print(y)
print(np.unique(y))

[1 9 5 4 9 1]
[1 4 5 9]
[[1 9 5]
 [4 9 1]]
[1 4 5 9]


In [97]:
# 20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, 
# unique values in array1 that are not in array2.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.setdiff1d(x,y)) #elements which are in x but not in y
print(np.setdiff1d(y,x)) #elements which are in y but not in x

[1 9 5 4]
[5 1 7 2 4 8]
[9]
[2 7 8]
