In [1]:
import numpy as np

In [22]:
# 1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

print("Sum:", np.add(4.0,1.2))

print("Difference:", np.subtract(4.0,1.2))

print("Product:", np.multiply(4.0,1.2))

print("Division:", np.divide(4.0,1.2))

Sum: 5.2
Difference: 2.8
Product: 4.8
Division: 3.3333333333333335


In [18]:
# 2. Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations 
# of the inputs in base-2.

a = np.log(2e-25)
print(a)

b = np.log(21e-25)
print(b)

print(np.logaddexp(a,b))

print(np.logaddexp2(a,b))

-56.8714801442912
-54.52010488712772
-54.429133108921995
-54.261936791001034


In [25]:
# 3. Write a NumPy program to get true division of the element-wise array inputs.

x = np.array([1,9,8,3,2])
print(x)

#true division works with dividing element-wise array inputs by a number 
print("True division by 2:", np.true_divide(x,2))
print("True division by 5:", np.true_divide(x,2.5))

[1 9 8 3 2]
True division by 2: [0.5 4.5 4.  1.5 1. ]
True division by 5: [0.4 3.6 3.2 1.2 0.8]


In [27]:
# 4. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs. 

x = np.array([1,9,8,3,2])
print(x)

#floor division either gives the largest integer smaller than or equal to the division of inputs
print(np.floor_divide(x,2))
print(np.floor_divide(x,3))

[1 9 8 3 2]
[0 4 4 1 1]
[0 3 2 1 0]


In [29]:
# 5. Write a NumPy program to get the powers of an array values element-wise.

x = np.array([1,9,8,3,2])
print(x)

print(np.power(x,2))     #power 2
print(np.power(x,3))     #power 3

[1 9 8 3 2]
[ 1 81 64  9  4]
[  1 729 512  27   8]


In [30]:
# 6. Write a NumPy program to get the element-wise remainder of an array of division. 

x = np.array([1,9.2,8.5,1.3,2])
print(x)

print(np.remainder(x,2))     
print(np.remainder(x,3))     

[1.  9.2 8.5 1.3 2. ]
[1.  1.2 0.5 1.3 0. ]
[1.  0.2 2.5 1.3 2. ]


In [31]:
# 7. Write a NumPy program to calculate the absolute value element-wise. 

x = np.array([-1,9.2,-8.5,1.3,2])
print(x)

print(np.abs(x))

[-1.   9.2 -8.5  1.3  2. ]
[1.  9.2 8.5 1.3 2. ]


In [34]:
# 8. Write a NumPy program to round array elements to the given number of decimals. 

print(np.round([7.2,3.5,0.9]))                      #general rounding up
print(np.round([7.20,3.5672,0.9123], decimals=2))   #two two decimal places

[7. 4. 1.]
[7.2  3.57 0.91]
[7. 4. 1.]


In [35]:
# 9. Write a NumPy program to round elements of the array to the nearest integer. 

# rounding elements to the nearest integer
print(np.rint([7.2,3.5,0.9,6.1,110.3]))

[  7.   4.   1.   6. 110.]


In [38]:
# 10. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array. 

print(np.floor([7.2,3.5,0.9,6.1,110.3]))
print(np.ceil([7.2,3.5,0.9,6.1,110.3]))
print(np.trunc([7.2,3.5,0.9,6.1,110.3]))

[  7.   3.   0.   6. 110.]
[  8.   4.   1.   7. 111.]
[  7.   3.   0.   6. 110.]
