In [1]:
import numpy as np

In [2]:
# 1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

print("Sum:", np.add(4.0,1.2))

print("Difference:", np.subtract(4.0,1.2))

print("Product:", np.multiply(4.0,1.2))

print("Division:", np.divide(4.0,1.2))

Sum: 5.2
Difference: 2.8
Product: 4.8
Division: 3.3333333333333335


In [3]:
# 2. Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations 
# of the inputs in base-2.

a = np.log(2e-25)
print(a)

b = np.log(21e-25)
print(b)

print(np.logaddexp(a,b))

print(np.logaddexp2(a,b))

-56.8714801442912
-54.52010488712772
-54.429133108921995
-54.261936791001034


In [4]:
# 3. Write a NumPy program to get true division of the element-wise array inputs.

x = np.array([1,9,8,3,2])
print(x)

#true division works with dividing element-wise array inputs by a number 
print("True division by 2:", np.true_divide(x,2))
print("True division by 5:", np.true_divide(x,2.5))

[1 9 8 3 2]
True division by 2: [0.5 4.5 4.  1.5 1. ]
True division by 5: [0.4 3.6 3.2 1.2 0.8]


In [5]:
# 4. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs. 

x = np.array([1,9,8,3,2])
print(x)

#floor division either gives the largest integer smaller than or equal to the division of inputs
print(np.floor_divide(x,2))
print(np.floor_divide(x,3))

[1 9 8 3 2]
[0 4 4 1 1]
[0 3 2 1 0]


In [6]:
# 5. Write a NumPy program to get the powers of an array values element-wise.

x = np.array([1,9,8,3,2])
print(x)

print(np.power(x,2))     #power 2
print(np.power(x,3))     #power 3

[1 9 8 3 2]
[ 1 81 64  9  4]
[  1 729 512  27   8]


In [7]:
# 6. Write a NumPy program to get the element-wise remainder of an array of division. 

x = np.array([1,9.2,8.5,1.3,2])
print(x)

print(np.remainder(x,2))     
print(np.remainder(x,3))     

[1.  9.2 8.5 1.3 2. ]
[1.  1.2 0.5 1.3 0. ]
[1.  0.2 2.5 1.3 2. ]


In [8]:
# 7. Write a NumPy program to calculate the absolute value element-wise. 

x = np.array([-1,9.2,-8.5,1.3,2])
print(x)

print(np.abs(x))

[-1.   9.2 -8.5  1.3  2. ]
[1.  9.2 8.5 1.3 2. ]


In [9]:
# 8. Write a NumPy program to round array elements to the given number of decimals. 

print(np.round([7.2,3.5,0.9]))                      #general rounding up
print(np.round([7.20,3.5672,0.9123], decimals=2))   #two two decimal places

[7. 4. 1.]
[7.2  3.57 0.91]


In [10]:
# 9. Write a NumPy program to round elements of the array to the nearest integer. 

# rounding elements to the nearest integer
print(np.rint([7.2,3.5,0.9,6.1,110.3]))

[  7.   4.   1.   6. 110.]


In [11]:
# 10. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array. 

print(np.floor([7.2,3.5,0.9,6.1,110.3]))
print(np.ceil([7.2,3.5,0.9,6.1,110.3]))
print(np.trunc([7.2,3.5,0.9,6.1,110.3]))

[  7.   3.   0.   6. 110.]
[  8.   4.   1.   7. 111.]
[  7.   3.   0.   6. 110.]


In [12]:
# 11. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.

x = np.arange(15).reshape((5,3))
print(x)

y = np.arange(6).reshape((3,2))
print(y)

print(np.dot(x,y))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [13]:
# 12. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of 
# complex numbers.

x = np.array([1+2j, 3-1j, 6+4j, 2-5j])
print(x)

y = np.array([6+1j, 4-2j, 1+1j, 2-7j])
print(y)

print(np.dot(x,y))

[1.+2.j 3.-1.j 6.+4.j 2.-5.j]
[6.+1.j 4.-2.j 1.+1.j 2.-7.j]
(-15-11j)


In [14]:
# 13. Write a NumPy program to create an inner product of two arrays. 

x = np.arange(6).reshape((3,2))
print(x)

y = np.arange(6).reshape((3,2))
print(y)

print(np.inner(x,y))

[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 41]]


In [15]:
# 14. Write a NumPy program to generate inner, outer, and cross products of matrices and vectors.

x = np.array([2,9,1])
print(x)

y = np.array([7,1,3])
print(y)

print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

[2 9 1]
[7 1 3]
26
[[14  2  6]
 [63  9 27]
 [ 7  1  3]]
[ 26   1 -61]


In [16]:
# 15. Write a NumPy program to generate a matrix product of two arrays.

x = np.array([2,9,1])
print(x)

y = np.array([7,1,3])
print(y)

print(np.matmul(x,y))  #in np.matmul multiplication with scalar is not allowed as in np.dot

[2 9 1]
[7 1 3]
26


In [17]:
# 16. Write a NumPy program to find the roots of the following polynomials.
# a) x2 - 4x + 7
# b) x4 - 11x3 + 9x2 + 11x - 10

print(np.roots([1,-4,7]))   #coffecients of the first polynomial
print(np.roots([1,-11,9,11,-10]))     #coffecients of the second polynomial

[2.+1.73205081j 2.-1.73205081j]
[10.+0.0000000e+00j -1.+0.0000000e+00j  1.+9.6357437e-09j
  1.-9.6357437e-09j]


In [18]:
# 17. Write a NumPy program to compute the following polynomial values. 

# a) x2 − 4x + 7, when x = 2
# b) x4 − 11x3 + 9x2 + 11x – 10, when x = 3

print(np.polyval([1,-4,7],2))
print(np.polyval([1,-11,9,11,-10],3))

3
-112


In [19]:
# 18. Write a NumPy program to add one polynomial to another, subtract one polynomial from another, multiply one 
# polynomial by another and divide one polynomial by another.

#give coefficients as input
x = (1,-4,7)
y = (10,5,-4)

print(np.polyadd(x,y))
print(np.polysub(x,y))
print(np.polymul(x,y))
print(np.polydiv(x,y))

[11  1  3]
[-9 -9 11]
[ 10 -35  46  51 -28]
(array([0.1]), array([-4.5,  7.4]))


In [20]:
# 19. Write a NumPy program to calculate mean across dimension, in a 2D numpy array.

x = np.array([[1,9],[13,5]])
print(x)

print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

[[ 1  9]
 [13  5]]
[7. 7.]
[5. 9.]


In [21]:
# 20. Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard 
# deviation of the array elements.

x = np.random.rand(1,1001)
print(x)

print("Mean                ", x.mean())
print("Variance            ", x.var())
print("Standard Deviation  ", x.std())

[[0.94701299 0.26025778 0.93174942 ... 0.9605203  0.49231707 0.61636376]]
Mean                 0.5043521030609126
Variance             0.08518479294787894
Standard Deviation   0.29186433997300687


In [22]:
# 21. Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.

x = np.array([0,0,1])
print(x)

print("Sine     ", np.sin(x))
print("Cosine   ", np.cos(x))
print("Tangent  ", np.tan(x))

[0 0 1]
Sine      [0.         0.         0.84147098]
Cosine    [1.         1.         0.54030231]
Tangent   [0.         0.         1.55740772]


In [23]:
# 22. Write a NumPy program to calculate inverse sine, inverse cosine, and inverse tangent for all elements in a 
# given array.

x = np.array([0,0,1])
print(x)

print("Inverse Sine     ", np.arcsin(x))
print("Inverse Cosine   ", np.arccos(x))
print("Inverse Tangent  ", np.arctan(x))

[0 0 1]
Inverse Sine      [0.         0.         1.57079633]
Inverse Cosine    [1.57079633 1.57079633 0.        ]
Inverse Tangent   [0.         0.         0.78539816]


In [24]:
# 23. Write a NumPy program to convert angles from radians to degrees for all elements in a given array.

x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi/3])
print(x)

print(np.degrees(x))

[-3.14159265 -1.57079633  1.57079633  1.04719755]
[-180.  -90.   90.   60.]


In [25]:
# 24. Write a NumPy program to convert angles from degrees to radians for all elements in a given array.

x = np.array([-180, -90, 90, 60])
print(x)

print(np.radians(x))

[-180  -90   90   60]
[-3.14159265 -1.57079633  1.57079633  1.04719755]


In [26]:
# 25. Write a NumPy program to calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent for all elements 
# in a given array.

x = np.array([0,0,1])
print(x)

print("Hyperbolic Sine     ", np.sinh(x))
print("Hyperbolic Cosine   ", np.cosh(x))
print("Hyperbolic Tangent  ", np.tanh(x))

[0 0 1]
Hyperbolic Sine      [0.         0.         1.17520119]
Hyperbolic Cosine    [1.         1.         1.54308063]
Hyperbolic Tangent   [0.         0.         0.76159416]


In [27]:
# 26. Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of decimals) 
# of the input, element-wise of a given array.

x = np.array([5.3, 0.1, 0.99, 21.3, 14.5])
print(x)

print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))
print(np.round(x))

[ 5.3   0.1   0.99 21.3  14.5 ]
[ 5.  0.  0. 21. 14.]
[ 6.  1.  1. 22. 15.]
[ 5.  0.  0. 21. 14.]
[ 5.  0.  1. 21. 14.]


In [28]:
# 27. Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each 
# of the 3 columns and sum over columns for each of the 2 rows of a given 2x3 array. 

x = np.array([[9,8,3],[1,0,5]])
print(x)

print(np.cumsum(x))
print(np.cumsum(x, axis=0))
print(np.cumsum(x, axis=1))

[[9 8 3]
 [1 0 5]]
[ 9 17 20 21 21 26]
[[ 9  8  3]
 [10  8  8]]
[[ 9 17 20]
 [ 1  1  6]]


In [29]:
# 28. Write a NumPy program to calculate cumulative product of the elements along a given axis, product over rows for 
# each of the 3 columns and product over columns for each of the 2 rows of a given 2x3 array. 

x = np.array([[9,8,3],[1,0,5]])
print(x)

print(np.cumprod(x))
print(np.cumprod(x, axis=0))
print(np.cumprod(x, axis=1))

[[9 8 3]
 [1 0 5]]
[  9  72 216 216   0   0]
[[ 9  8  3]
 [ 9  0 15]]
[[  9  72 216]
 [  1   0   0]]


In [30]:
# 29. Write a NumPy program to calculate the difference between neighboring elements, element-wise of a given array.

x = np.array([9,6,1,2,6,7])
print(x)

print(np.diff(x))

[9 6 1 2 6 7]
[-3 -5  1  4  1]


In [31]:
# 30. Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend 
# [0, 0] and append[200] to a given array.

x = np.array([9,6,1,2,6,7])
print(x)

print(np.diff(x))
print(np.append([0,0], x))
print(np.append(x, [200]))



[9 6 1 2 6 7]
[-3 -5  1  4  1]
[0 0 9 6 1 2 6 7]
[  9   6   1   2   6   7 200]


In [32]:
# 31. Write a NumPy program to compute e^x, element-wise of a given array. 

x = np.array([1,7,9,5])
print(x)

print(np.exp(x))

[1 7 9 5]
[2.71828183e+00 1.09663316e+03 8.10308393e+03 1.48413159e+02]


In [33]:
# 32. Write a NumPy program to calculate exp(x) - 1 for all elements in a given array. 

x = np.array([1,7,9,5])
print(x)

y = np.expm1(x)
print(y)

z = np.exp(x) - 1
print(z)

assert(np.allclose(y,z))  #to check if both are equal or not

[1 7 9 5]
[1.71828183e+00 1.09563316e+03 8.10208393e+03 1.47413159e+02]
[1.71828183e+00 1.09563316e+03 8.10208393e+03 1.47413159e+02]


In [34]:
# 33. Write a NumPy program to calculate 2^p for all elements in a given array. 

x = np.array([1,7,9,5])
print(x)

y = 2 ** x
print(y)

z = np.exp2(x)
print(z)

assert(np.allclose(y,z))

[1 7 9 5]
[  2 128 512  32]
[  2. 128. 512.  32.]


In [35]:
# 34. Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array. 

x = np.array([np.e, np.e**2, np.e**3])
print(x)

print(np.log(x))
print(np.log10(x))
print(np.log2(x))

[ 2.71828183  7.3890561  20.08553692]
[1. 2. 3.]
[0.43429448 0.86858896 1.30288345]
[1.44269504 2.88539008 4.32808512]


In [36]:
# 35. Write a NumPy program to compute the natural logarithm of one plus each element of a given array in 
# floating-point accuracy.

x = np.array([np.e, np.e**2, np.e**3])
print(x)

y = np.log1p(x)
print(y)

[ 2.71828183  7.3890561  20.08553692]
[1.31326169 2.12692801 3.04858735]


In [37]:
# 36. Write a NumPy program to check element-wise True/False of a given array where signbit is set. 

x = np.array([1,-4,6,0,-9,-11,2,4,3,-6])
print(x)

y = np.signbit(x)
print(y)

[  1  -4   6   0  -9 -11   2   4   3  -6]
[False  True False False  True  True False False False  True]


In [38]:
# 37. Write a NumPy program to change the sign of a given array to that of a given array, element-wise. 

x = np.array([1,-4,6,0,-9,-11,2,4,3,-6])
print(x)

y = -2
z = 6

print(np.copysign(x,y))
print(np.copysign(x,z))

[  1  -4   6   0  -9 -11   2   4   3  -6]
[ -1.  -4.  -6.  -0.  -9. -11.  -2.  -4.  -3.  -6.]
[ 1.  4.  6.  0.  9. 11.  2.  4.  3.  6.]


In [39]:
# 38. Write a NumPy program to compute numerical negative value for all elements in a given array. 

x = np.array([1,-4,6,0,-9,-11,2,4,3,-6])
print(x)

y = -x
z = np.negative(x)

print(y)
print(z)

assert np.allclose(y,z)

[  1  -4   6   0  -9 -11   2   4   3  -6]
[-1  4 -6  0  9 11 -2 -4 -3  6]
[-1  4 -6  0  9 11 -2 -4 -3  6]


In [40]:
# 39. Write a NumPy program to compute the reciprocal for all elements in a given array. 

x = np.array([1,-4,10,4,-2,-8,2,4,1,-6])
print(x)

print(np.reciprocal(x))

[ 1 -4 10  4 -2 -8  2  4  1 -6]
[1 0 0 0 0 0 0 0 1 0]


In [41]:
# 40. Write a NumPy program to compute x^y, element-wise where x, y are two given arrays. 

x = np.array([1,4,10,4,6,8,2])
print(x)

y = np.array([1,2,5,4,6,3,2])
print(y)

print(np.power(x,y))

[ 1  4 10  4  6  8  2]
[1 2 5 4 6 3 2]
[     1     16 100000    256  46656    512      4]


In [42]:
# 41. Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array.

x = np.array([1,-4,10,4,-2,-8,0,4,1,-6])
print(x)

x[x > 0] = 1   #1 when the sign is positive
x[x < 0] = -1  #-1 when the sign is negative, else 0
print(x)

[ 1 -4 10  4 -2 -8  0  4  1 -6]
[ 1 -1  1  1 -1 -1  0  1  1 -1]
