In [2]:
import numpy as np

In [2]:
# 1. Write a NumPy program to print the NumPy version in your system.

print(np.__version__)

1.17.2


In [3]:
# 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

lst = [12.23, 13.32, 100, 36.32]
print(np.array(lst))

[ 12.23  13.32 100.    36.32]


In [4]:
# 3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

x = np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [5]:
# 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [6]:
# 5. Write a NumPy program to create an array with values ranging from 12 to 38.

x = np.arange(12,39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [7]:
# 6. Write a NumPy program to reverse an array (first element becomes last).

x = np.array([1,2,0,9,6,4])
print(x)
print(x[::-1])

[1 2 0 9 6 4]
[4 6 9 0 2 1]


In [8]:
# 7. Write a NumPy program to convert an array to a float type.

x = np.array([18,25,10,19,61,14])
print(x)
print(x.astype('float32'))

[18 25 10 19 61 14]
[18. 25. 10. 19. 61. 14.]


In [9]:
# 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

x = np.ones(16).reshape(4,4)
print(x)
y = np.zeros(4).reshape(2,2)
print(y)
x[1:3,1:3] = y
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [10]:
# 9. Write a NumPy program to add a border (filled with 0's) around an existing array. 

x = np.ones(16).reshape(4,4)
print(x)
x = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
# 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern. 

x = np.zeros(64).reshape(8,8)
#print(x)
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [12]:
# 11. Write a NumPy program to convert a list and tuple into arrays.

lst = [1,2,7,0,4,8]
print(np.array(lst))
#print(np.asarray(lst)) 

tpl_1 = [1, "ankur", "c"]
tpl_2 = [2.5, 7, 3.2]
tpl_3 = ([1,2,5],[3,0,9])
print(np.array(tpl_1))
print(np.array(tpl_2))
print(np.array(tpl_3))

[1 2 7 0 4 8]
['1' 'ankur' 'c']
[2.5 7.  3.2]
[[1 2 5]
 [3 0 9]]


In [13]:
# 12. Write a NumPy program to append values to the end of an array. 

x = np.array([1,7,8,4])
y = np.array([5,9,11])
print(x)
print(y)
z1 = np.append(x,y)
z2 = np.append(y,x)
print(z1)
print(z2)

[1 7 8 4]
[ 5  9 11]
[ 1  7  8  4  5  9 11]
[ 5  9 11  1  7  8  4]


In [14]:
# 13. Write a NumPy program to create an empty and a full array. 

x = np.empty((2,3))
print(x)
y = np.full((2,3),4)
print(y)

[[4.9e-324 9.9e-324 2.5e-323]
 [1.5e-323 0.0e+000 4.4e-323]]
[[4 4 4]
 [4 4 4]]


In [15]:
# 14. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values 
# are stored into a NumPy array.

x = np.array([32,109,67])
print("Centigrade degrees: ", x, "degrees C")
y = (x * 1.8) + 32
print("Fahrenheit degrees: ", y, "degrees F")

Centigrade degrees:  [ 32 109  67] degrees C
Fahrenheit degrees:  [ 89.6 228.2 152.6] degrees F


In [16]:
# 15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers. 

x = np.array([1+2j])
print(x)
print(x.real)
print(x.imag)

y = np.array([[2+3j],[4+6j]])
print(y)
print(y.real)
print(y.imag)

[1.+2.j]
[1.]
[2.]
[[2.+3.j]
 [4.+6.j]]
[[2.]
 [4.]]
[[3.]
 [6.]]


In [17]:
# 16. Write a NumPy program to find the number of elements of an array, length of one array element in bytes 
# and total bytes consumed by the elements. 

x = np.array([[2,5],[4,6]])
print(x)
print("Number of elements in the array:" , x.size)
print("Length of one array element:", x.itemsize, "bytes")
print("Total bytes consumed by the array elements", x.nbytes, "bytes")

[[2 5]
 [4 6]]
Number of elements in the array: 4
Length of one array element: 8 bytes
Total bytes consumed by the array elements 32 bytes


In [18]:
# 17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.in1d(x,y)) 

[1 9 5 4]
[5 1 7 2 4 8]
[ True False  True  True]


In [19]:
# 18. Write a NumPy program to find common values between two arrays. 

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.intersect1d(x,y))

[1 9 5 4]
[5 1 7 2 4 8]
[1 4 5]


In [20]:
# 19. Write a NumPy program to get the unique elements of an array.

x = np.array([1,9,5,4,9,1])
print(x)
print(np.unique(x))


y = np.array([[1,9,5],[4,9,1]])
print(y)
print(np.unique(y))

[1 9 5 4 9 1]
[1 4 5 9]
[[1 9 5]
 [4 9 1]]
[1 4 5 9]


In [21]:
# 20. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, 
# unique values in array1 that are not in array2.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.setdiff1d(x,y)) #elements which are in x but not in y
print(np.setdiff1d(y,x)) #elements which are in y but not in x

[1 9 5 4]
[5 1 7 2 4 8]
[9]
[2 7 8]


In [22]:
# 21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, 
# unique values that are in only one (not both) of the input arrays.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.setxor1d(x,y)) 

[1 9 5 4]
[5 1 7 2 4 8]
[2 7 8 9]


In [24]:
# 22. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of 
# values that are in either of the two input arrays.

x = np.array([1,9,5,4])
print(x)
y = np.array([5,1,7,2,4,8])
print(y)
print(np.union1d(x,y))

[1 9 5 4]
[5 1 7 2 4 8]
[1 2 4 5 7 8 9]


In [28]:
# 23. Write a NumPy program to test whether all elements in an array evaluate to True. 

print(np.all([[True,True],[False,True]]))
print(np.all([[True,True,True],[True,True,True]]))
print(np.all([0,1,2,3]))
print(np.all([1,1,2,3]))
#returns true if all values are true

False
True
False
True


In [33]:
# 24. Write a NumPy program to test whether any array element along a given axis evaluates to True.

print(np.any([[True,True],[False,True]]))
print(np.any([[True,True,True],[True,True,True]]))
print(np.any([0,1,2,3]))
print(np.any([1,1,2,3]))
print(np.any([0,0,0]))

True
True
True
True
False


In [41]:
# 25. Write a NumPy program to construct an array by repeating.

print(np.tile(3,2))   #repeats '3' 2 times
print(np.tile([[3,2],[1,0]], 3))   #repeats each array 3 times

[3 3]
[[3 2 3 2 3 2]
 [1 0 1 0 1 0]]


In [59]:
# 26. Write a NumPy program to repeat elements of an array.

print(np.repeat(3,2))   #repeats '3' 2 times
print(np.repeat([[3,2],[1,0]], 3))   #repeats each element 3 times and return a 1d array
print(np.repeat([[3,2],[1,0]], 2, axis = 1)) #repeats each element 2 times along axis = 1 that is columns
print(np.repeat([[3,2],[1,0]], 2, axis = 0)) #repeats each element 2 times along axis = 0 that is rows

#difference between np.repeat and tile:
#np.repeat repeats element of an array
#np.tile construct an array by repeating the array the number of times given. 

[3 3]
[3 3 3 2 2 2 1 1 1 0 0 0]
[[3 3 2 2]
 [1 1 0 0]]
[[3 2]
 [3 2]
 [1 0]
 [1 0]]


In [53]:
# 27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
  
print(np.argmax([3,2,5,6,9]), np.argmin([3,2,5,6,9])) 
print(np.argmax([[3,2],[0,1]], axis = 1), np.argmin([[3,2],[0,1]], axis = 1)) 
print(np.argmax([[0,2],[1,3]], axis = 0), np.argmin([[0,2],[1,3]], axis = 0)) 

4 1
[0 1] [1 0]
[1 1] [0 0]


In [58]:
# 28. Write a NumPy program compare two given arrays.

x = np.array([1,9,5,4])
y = np.array([6,9,0,5])

print(np.equal(x,y))
print(np.greater(x,y))
print(np.less(x,y))
print(np.greater_equal(x,y))
print(np.less_equal(x,y))

[False  True False False]
[False False  True False]
[ True False False  True]
[False  True  True False]
[ True  True False  True]


In [72]:
# 29. Write a NumPy program to sort an along the first, last axis of an array. 

x = np.array([[1,9],[2,3]])
print(x)
print(np.sort(x, axis = 0))
print("*****")
y = np.array([[2,1],[3,5]])
print(y)
print(np.sort(y, axis = 1))
print("*****")
z = np.array([[1,9,3],[2,5,3]])
print(z)
print(np.sort(z, axis = 0))

[[1 9]
 [2 3]]
[[1 3]
 [2 9]]
*****
[[2 1]
 [3 5]]
[[1 2]
 [3 5]]
*****
[[1 9 3]
 [2 5 3]]
[[1 5 3]
 [2 9 3]]


In [89]:
# 30. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, 
# then by first name).

x_first = ("Alisha","Mayank","Meenu","Ajay")
x_last = ("Rastogi","Khanna","Garg","Garg")
x = np.lexsort((x_first, x_last))
# "Alisha Rastogi", "Mayank Khanna", "Meenu Garg", "Ajay Gupta" - Pairs of first and last names
# lexsort will first sort according to the last key, then second last and so on
print(x)

[3 2 1 0]


In [101]:
# 31. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

x = np.array([[11,9,5,14],[1,3,18,91]])
print(x[x>10])
print(np.nonzero(x>10))

[11 14 18 91]
(array([0, 0, 1, 1]), array([0, 3, 2, 3]))


In [106]:
# 32. Write a NumPy program to save a NumPy array to a text file.

x = np.array([[1,2],[5,0]])
print(x)
np.savetxt('Array_to_text.txt', x)

[[1 2]
 [5 0]]


In [112]:
# 33. Write a NumPy program to find the memory size of a NumPy array.

x = np.array([[1,2],[5,0]])
print(x.nbytes)

y = np.array([1,2,3,4,5,6,7,8])
print(y.size * y.itemsize)

32
64


In [119]:
# 34. Write a NumPy program to create an array of ones and an array of zeros. 

x = np.zeros(4, dtype = np.int)
print(x)

y = np.ones((2,3), dtype = np.int)
print(y)

[0 0 0 0]
[[1 1 1]
 [1 1 1]]


In [131]:
# 35. Write a NumPy program to change the dimension of an array.

x = np.array([[2,3],[1,0]])
print(x)
print(x.reshape(4,1))

y = np.array([[1,2,3],[7,1,0]])
print(y)
print(y.shape)
y.shape = (3,2)
print(y)

[[2 3]
 [1 0]]
[[2]
 [3]
 [1]
 [0]]
[[1 2 3]
 [7 1 0]]
(2, 3)
[[1 2]
 [3 7]
 [1 0]]


In [132]:
# 36. Write a NumPy program to create a contiguous flattened array. 

x = np.array([[2,3],[1,0]])
print(x)
print(np.ravel(x))

[[2 3]
 [1 0]]
[2 3 1 0]


In [148]:
# 37. Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), 
# also print the shape, type and data type of the array. 

x = np.array([[1,8,2],[0,4,3]], dtype = np.int32)
print(type(x))
print(np.shape(x))
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


In [150]:
# 38. Write a NumPy program to create a new shape to an array without changing its data. 

x = np.array([[1,4,9],[0,5,3]])
print(x)
print(x.reshape(3,2))

[[1 4 9]
 [0 5 3]]
[[1 4]
 [9 0]
 [5 3]]


In [158]:
# 39. Write a NumPy program to change the data type of an array. 

x = np.array([[1,4,9],[0,5,3]])
print(x)
print(x.dtype)
y = x.astype(np.float16)
print(y)
print(y.dtype)

[[1 4 9]
 [0 5 3]]
int64
[[1. 4. 9.]
 [0. 5. 3.]]
float16


In [162]:
# 40. Write a NumPy program to create a new array of 3*5, filled with 2.

x = np.ones((3,5), dtype = np.int16) * 2
print(x)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [168]:
# 41. Write a NumPy program to create an array of 10's with the same shape and type of a given array.

x = np.arange(4, dtype = np.int32)
print(x)
y = np.full_like(x, 10) #x is the array type required and 10 is the fill value for that array
print(y)

[0 1 2 3]
[10 10 10 10]


In [174]:
# 42. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere. 

x = np.eye(3)  #write 3 for 3d array, 2 for 2d and 1 for 1d array
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [176]:
# 43. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

x = np.diag([4,5,6,8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [178]:
# 44. Write a NumPy program to create a 1-D array going from 0 to 50 and an array from 10 to 50.

x = np.arange(0,50)
print(x)

y = np.arange(10,50)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [180]:
# 45. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive. 

x = np.linspace(2.5,6.5,30)
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [183]:
# 46. Write a NumPy program to create a 1-D array of 20 elements spaced evenly on a log scale between 2. and 5., 
# exclusive. 

x = np.logspace(2,5,20, endpoint = False)
print(x)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [188]:
# 47. Write a NumPy program to create an array which looks like below array. 

x = np.tri(4,3,-1)  #tri is triangle with 1's and 0's; 1s at and below the given diagonal and 0s elsewhere
#-1 because we want array having 1s below the main diagonal (1 would make it above and 0 would make it on diagonal)
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [196]:
# 48. Write a NumPy program to create an array which looks like below array. 

x = np.triu(np.arange(2,14).reshape(4,3),-1) #element below the kth diagonal will be zero
#-1 will make only the elements below the main diagonal 0, 1 will make elements above the main diagonal 0 and 
# 0 will make elements till the main diagonal 0
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 0  9 10]
 [ 0  0 13]]


In [201]:
# 49. Write a NumPy program to collapse a 3-D array into one dimension array. 

x = np.arange(8).reshape(2,2,2)
print(x)
print(np.ravel(x))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[0 1 2 3 4 5 6 7]


In [210]:
# 50. Write a NumPy program to find the 4th element of a specified array. 

x = np.arange(8)
print(x)
print(x[3])

y = np.arange(8).reshape(2,4)
print(y)
z = np.ravel(y)
print(z)
print(z[3])

a = np.arange(8).reshape(2,4)
print(y)
b = a.flat
print(b)
print(b[3])

[0 1 2 3 4 5 6 7]
3
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
3
[[0 1 2 3]
 [4 5 6 7]]
3


In [214]:
# 51. Write a NumPy program to interchange two axes of an array.

x = np.arange(8).reshape(2,4)
print(x)
y = np.swapaxes(x,0,1)
print(y)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [221]:
# 52. Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order. 

x = np.zeros((2,3,4))
print(x.shape)
y = np.moveaxis(x,-1,0) #-1 is the axis to be moved and 0 is its final position in the array
print(y.shape)
z = np.moveaxis(x,0,-1)
print(z.shape)

(2, 3, 4)
(4, 2, 3)
(3, 4, 2)


In [234]:
# 53. Write a NumPy program to move the specified axis backwards, until it lies in a given position. 

x = np.ones((3,4,5,6))
print(x.shape)
y = np.rollaxis(x, 3, 1) #Move the following 3rd array axes to first position.
print(y.shape)
a = np.zeros((3,4,5,6))
print(a.shape)
b = np.rollaxis(a, 2, 1)
print(b.shape)

(3, 4, 5, 6)
(3, 6, 4, 5)
(3, 4, 5, 6)
(3, 5, 4, 6)


In [236]:
# 54. Write a NumPy program to convert specified inputs to arrays with at least one dimension. 

x = 12
y = np.atleast_1d(x)  #scalar input is convereted to 1d array
print(y)

a = np.arange(6).reshape(3,2)
print(a)
b = np.atleast_1d(a)   #higher dimensional arrays are preserved
print(b)

[12]
[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [247]:
# 55. Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions. 

x = 12
y = np.atleast_2d(x)  
print(y)
print("****")
c = np.atleast_3d(x)
print(c)
print("****")
a = np.arange(6).reshape(3,2)
#print(a)
b = np.atleast_2d(a)   
print(b)
print("****")
d = np.atleast_3d(a)
print(d)

[[12]]
****
[[[12]]]
****
[[0 1]
 [2 3]
 [4 5]]
****
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]


In [253]:
# 56. Write a NumPy program to insert a new axis within a 2-D array. 

x = np.array([1,2])
print(x.shape)
y = np.expand_dims(x, 1) #new axis will be inserted at axis = 1
print(y.shape)

a = np.array([[1,2],[9,3]])
print(a.shape)
b = np.expand_dims(a,2) #new axis will be inserted at axis = 2
print(b.shape)

(2,)
(2, 1)
(2, 2)
(2, 2, 1)


In [260]:
# 57. Write a NumPy program to remove single-dimensional entries from a specified shape. 

x = np.array([[1],[9],[3]])
print(x.shape)
print(np.squeeze(x).shape) #removes the 1-dimensional entries from an array

y = np.ones((2,3,4,1))
print(y.shape)
print(np.squeeze(y).shape)

(3, 1)
(3,)
(2, 3, 4, 1)
(2, 3, 4)


In [267]:
# 58. Write a NumPy program to concatenate two 2-dimensional arrays. 

x = np.array([[[2,3],[1,0]],[[1,9],[3,4]]])
print(x)
print("****")
y = np.array([[[1,5],[0,5]],[[4,4],[1,0]]])
print(y)
print("****")
print(np.concatenate((x,y),axis = 0))
print("****")
print(np.concatenate((x,y),axis = 1))
print("****")
print(np.concatenate((x,y),axis = 2))

[[[2 3]
  [1 0]]

 [[1 9]
  [3 4]]]
****
[[[1 5]
  [0 5]]

 [[4 4]
  [1 0]]]
****
[[[2 3]
  [1 0]]

 [[1 9]
  [3 4]]

 [[1 5]
  [0 5]]

 [[4 4]
  [1 0]]]
****
[[[2 3]
  [1 0]
  [1 5]
  [0 5]]

 [[1 9]
  [3 4]
  [4 4]
  [1 0]]]
****
[[[2 3 1 5]
  [1 0 0 5]]

 [[1 9 4 4]
  [3 4 1 0]]]


In [274]:
# 59. Write a NumPy program to convert 1-D arrays as columns into a 2-D array.

x = np.array((0,2,1))
print(x)
y = np.array((7,3,5))
print(y)
print(np.vstack((x,y)))  #method 1
print(np.column_stack((x,y))) #method 2

[0 2 1]
[7 3 5]
[[0 2 1]
 [7 3 5]]
[[0 7]
 [2 3]
 [1 5]]


In [280]:
# 60. Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array. 

x = np.array((0,2,1))
print(x)
y = np.array((7,3,5))
print(y)
print(np.dstack((x,y)))
print(np.dstack((x,y)).shape)

[0 2 1]
[7 3 5]
[[[0 7]
  [2 3]
  [1 5]]]
(1, 3, 2)


In [6]:
# 61. Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 
# elements in the original order. 

x = np.arange(14)
print(x)
print(np.split(x,[2,6]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[array([0, 1]), array([2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13])]


In [11]:
# 62. Write a NumPy program to split of an array of shape 4x4 into two arrays along the second axis. 

x = np.arange(16).reshape((4,4))
print(x)
print(np.hsplit(x, 2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [14]:
# 63. Write a NumPy program to get the number of nonzero elements in an array. 

x = np.array([[1,2,3],[10,0,9],[4,5,0],[2,5,4]])
print(x)
print(np.count_nonzero(x))

[[ 1  2  3]
 [10  0  9]
 [ 4  5  0]
 [ 2  5  4]]
10


In [17]:
# 64. Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

x = np.zeros(25).reshape((5,5))
print(x)
y = np.arange(5)
print(y)
x += y
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [31]:
# 65. Write a NumPy program to test whether specified values are present in an array. 

x = np.array([[1,2,7,0,5.1],[3,4.5,7.11,2,1]])
print(x)
print(5.1 in x)
print(2 in x)
print(75.6 in x)

[[1.   2.   7.   0.   5.1 ]
 [3.   4.5  7.11 2.   1.  ]]
True
True
False


In [33]:
# 66. Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded.

x = np.linspace(0,1,10, endpoint = False)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [35]:
# 67. Write a NumPy program to make an array immutable (read-only). 

x = np.arange(5)
print(x)
x.flags.writeable = False  #writing has been set to false to make it read only
x[3] = 9
print(x)

[0 1 2 3 4]


ValueError: assignment destination is read-only

In [49]:
# 68. Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100.

a = np.arange(100)
print(a)
b = a[(a % 3 == 0)|(a % 5 == 0)]     #multiple of 3 or 5 will cover all the common multiples too
print(b)
print(np.sum(b))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99  0  5 10 15 20 25 30 35 40 45 50 55 60 65
 70 75 80 85 90 95]
2633
*******
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [53]:
# 69. Write a NumPy program to create an array with 10^3 elements. 

x = np.arange(10**3)   #or np.arange(1e3)
print(x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [59]:
# 70. Write a NumPy program to create and display every element of a NumPy array.

x = np.arange(9)
print(x)
for i in np.nditer(x):
    #print(i)
    print(i, end ="")

[0 1 2 3 4 5 6 7 8]
012345678