In [1]:
import numpy as np

In [3]:
# 1. Write a NumPy program to generate five random numbers from the normal distribution. 

#size defines how many random numbers you want to generate 
#normal to get numbers in normal distribution
print(np.random.normal(size=5)) 

[-2.13104791  0.50696315  0.48970414  0.46509229 -0.790732  ]


In [5]:
# 2. Write a NumPy program to generate six random integers between 10 and 30.

#randint for random integers
print(np.random.randint(low=10, high=30, size=6))

[27 19 28 27 19 12]


In [6]:
# 3. Write a NumPy program to create a 3x3x3 array with random values. 

#random for any random values
print(np.random.random((3,3,3)))

[[[0.33756543 0.41366913 0.93522441]
  [0.15280021 0.17672765 0.97312188]
  [0.86427526 0.77059658 0.50812723]]

 [[0.10290498 0.69314183 0.01596975]
  [0.20939369 0.28113083 0.41510861]
  [0.25436676 0.49311265 0.5485813 ]]

 [[0.89014523 0.88187934 0.27403609]
  [0.74655025 0.64747528 0.91128969]
  [0.39069735 0.92161148 0.33754813]]]


In [9]:
# 4. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values. 

x = np.random.random((5,5))
print(x)
print(x.min())
print(x.max())

[[0.11001433 0.1937823  0.95843827 0.72681025 0.28841812]
 [0.47676413 0.4062704  0.62868342 0.44959016 0.16553678]
 [0.38835023 0.85810448 0.92447548 0.79858242 0.59691442]
 [0.6822069  0.11400708 0.18472984 0.37632925 0.8222329 ]
 [0.34964029 0.04497315 0.32194401 0.35481074 0.77072185]]
0.04497315278033531
0.9584382696211912


In [ ]:
# 5. 